# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql/mysql.sock:/var/run/mysqld/mysqld.sock:ro"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "todobackend"
      MYSQL_USER: "todo"
      MYSQL_PASSWORD: "password"
